/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package gradle.demo1

class App {
    String getGreeting() {
        return 'Hello from Akhaphon.'
    }

    static void main(String[] args) {
        println new App().greeting
    }
}
